### ISSUE TITLE
bumblebee get a error when start 

### ISSUE THREAD

**Issue by HuongAT** [Hoektronics/bumblebee#10]
this is log 
![screenshot from 2016-03-13 23 00 29](https://cloud.githubusercontent.com/assets/17767325/13729762/6b5eadb6-e96f-11e5-82c0-124cd1f27d8a.png)

I get this error when plugged 2 camera on a raspberry pi to control printers driver because I wanted to see two active printers how.
when there is a camera, it works normally, I think there is something abnormal in 108 lines in botqueueapi.py~
`response = self.session.send(request.prepare(), timeout=600)`
please help me fix it

**Comment by HuongAT** [comment]
@Jnesselr  please!

**Comment by Jnesselr** [comment]
I've spent the majority of my weekend trying to fix this and have been
refactoring the communications part to try and get everything to work
smoothly.

I do not get paid for this. This is not my full time job. I do this out of
love for the project. Please don't comment on a ticket trying to rush me.
Yes, I realize it's broken and not usable right now. But what you're doing
is making me not want to work on the project. It's not going to magically
make me move faster.

**Comment by HuongAT** [comment]
I apologize for past actions! Really, I do not mean to bother you so.
I was wrong to try to seek help without thinking about your job.
I sincerely apologize !
